### ISSUE TITLE
Regression in func_breakable_surf parsing

### ISSUE THREAD

**Issue by ItEndsWithTens** [Metapyziks/VMFInstanceInserter#22]
Finished another map a few days ago, and while working on it noticed that func_breakable_surf entities didn't appear correctly after VMFII processed the files. It looks like you fixed this once: https://github.com/Metapyziks/VMFInstanceInserter/commit/d58ba50a4467a6da14960f35e184436b9e95ac31 After you switched to FGD parsing, the problem unfortunately seems to have come back, since for some reason the upper/lowerleft and upper/lowerright keys aren't in any of the FGD files. The entity refers to something called "quadbounds", which isn't defined in any FGDs either, but which I take it is responsible for providing the four keys in question.

I was able to fix this in my own copy of the code by adding the keys to [the Entity entry in stTransformDict](https://github.com/Metapyziks/VMFInstanceInserter/blob/master/VMFInstanceInserter/VMFStructure.cs#L68):

```csharp
{ VMFStructureType.Entity, new Dictionary<String, TransformType>
{
    { "origin", TransformType.Position },
    { "angles", TransformType.Angle },
    { "targetname", TransformType.EntityName },
    { "parentname", TransformType.EntityName },
    { "lowerleft", TransformType.Position },
    { "lowerright", TransformType.Position },
    { "upperleft", TransformType.Position },
    { "upperright", TransformType.Position }
} },
```

In the past I've sent pull requests for things defined in the FGDs that needed special treatment, but this time I wasn't so sure of myself. Is this the right way to add an exception for something like func_breakable_surf?

**Comment by Metapyziks** [comment]
To be honest I can't remember if I had a nicer way of hardcoding things missing from FGD files, so I'll be happy to accept a pull request with the fix you described.
