### ISSUE TITLE
Support for other VMF-like formats/FGD based games

### ISSUE THREAD

**Issue by ItEndsWithTens** [Metapyziks/VMFInstanceInserter#25]
I really should have gotten on this a few months ago, but a parade of constant interruptions diverted my attention. Sorry for the delay.

I'm just wondering about your philosophy regarding support for other map formats like VMF. I participated in func_msgboard's ["Fire and Brimstone"](http://celephais.net/board/view_thread.php?id=61228) Quake map jam back in August, and being used to Source mapping in Hammer I desperately wanted to see instance support. I was desperate enough to add it myself: https://github.com/ItEndsWithTens/VMFInstanceInserter/tree/add_map_support

Valve's 220 .map and Jackhammer's .fgd formats are close enough to Source standards, thanks to the engine's lineage, that I only had to reformat the input before passing it to VMFII, then postprocess it a bit to write out a file palatable to Quake compilers. Things seemed to work out quite well (see "Princess of China" for the results), and though there are currently no editors that can actually display instance contents in their respective viewports, VMFII collapses everything as expected, name fix up, variable replacement, the whole nine yards.

Of course, this little project I took upon myself involved a much greater number and scope of changes than anything I've sent you before, namely my FGD cleaning methods, so I wasn't about to open a pull request over a thing like this. I'm not finished with my work quite yet (I'd still like to add support for older .map versions), but I figured the question is better asked late than never: are you interested in this type of extension to VMFII's target game? I understand it could easily become a burden, of course, so if you'd rather I just maintain my own fork with its own extra format support I won't take it personally.

**Comment by ItEndsWithTens** [comment]
The more I think about it the more I realize how intrusive this is; a dedicated executable, as a separate project, would probably accomplish the same thing without touching your code. I'll take a shot at writing a wrapper application to simply spit out some temporary files, call an unmodified release of VMFII, and postprocess the result. Should let me support whatever games I want without bugging you with stuff like this all the time. Goes to show how as great as a real project with a real deadline is for inspiring quick and dirty results, they can encourage people like me to miss the more sensible solutions.

Also I think I see a problem with my "CleanFGD" method that'll cause it to choke on some of the standard Source FGDs. Hopefully my wrapper experiment will work out and I can just nuke my whole add_map_support branch. May I ask what license you've published VMFII under? If this idea shows promise it'd be awfully convenient to just redistribute a copy of your executable alongside mine.

**Comment by Metapyziks** [comment]
Hi, really sorry that I hadn't replied earlier!

I don't have a problem with supporting other formats, although I would really like to rewrite VMFII before then as the current design was pretty much a quick hack to get instances working for my own project. Part of that rewrite would involve making the project more modular, so that different input and output formats can be specified in a clean way.

As for licensing, I'll put it under MIT for now so you're free to distribute it.

Again, apologies for the late reply.

**Comment by ItEndsWithTens** [comment]
That's incredible, thank you! No need to apologize, I understand you've got other projects demanding your attention. I had just wanted to keep the discussion up to date with my newer idea so you knew where I was going with all this.

I'm having some success with the wrapper so far, here's hoping it continues. I'll eventually start a dedicated thread for the project on [func_msgboard](http://celephais.net/board/forum.php), if you want to keep an eye out, but for reference [here's where the recent discussion started](http://celephais.net/board/view_thread.php?id=61211&start=153).

Your choice of license and quick commits are extremely generous, thanks again!

**Comment by ItEndsWithTens** [comment]
Forgot I left this issue open, sorry about that, but since it's still here I might as well mention the wrapper idea worked out splendidly! Just finished up the first release, you can find it at https://github.com/ItEndsWithTens/Quinstance if you're so inclined. I'll thank you one more time for the MIT license, and for VMFII itself!
